### PR TITLE
Create heidi_seibold.md

### PR DESCRIPTION
**Pull request by HeidiSeibold**
My story :smile:

### CODE REVIEW

**Comment by HeidiSeibold** [comment]
This is for issue #2

**Comment by trallard** [comment]
Thanks a lot Heidi!!!! will you be adding a profile picture too??? (not mandatory though)

**Comment by HeidiSeibold** [comment]
Oh yes. I am not sure, should this be in images/role_models ? The folder does not exist yet, but I can creat it.

**Comment by trallard** [comment]
Yes, since you're my first role model you'll have to create this folder!!!

Many thanks

**Comment by HeidiSeibold** [comment]
Is that how it's supposed to be?

**Comment by trallard** [comment]
Yes it looks good to me! 

🙌🏼

**Pull request merged**
